### ISSUE TITLE
Added support for 30C Max

### ISSUE THREAD

**Issue by CyberDefenseTiger** [pbulteel/eufy_vacuum#9]
I have a 30C max T2130 and I get the following error. 

RuntimeError: Unsupported model T2130

If it can be supported that would be great.  It is basically the same as the 30C from what i understand with more powerful suction.

I will try to help in any way you need it.

If you need any more information let me know.

Thank you for all your work on this in general though.

**Comment by gmac0612** [comment]
T2118 is the only model 'supported' in the code, so changing type: to anything other than T2118 in configuration.yaml will cause it to fail to load.

Change the relevant part of your configuration.yaml back to T2118, but retain the rest of the settings like IP, local key etc.

Check config, restart homeassistant & see what happens after that.

**Comment by CyberDefenseTiger** [comment]
Thank you for replying.  I had tried that and got the following error logs its why I tried the different model.

Logger: custom_components.eufy_vacuum.tuya
Source: custom_components/eufy_vacuum/tuya.py:403
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 9:49:01 AM (3 occurrences)
Last logged: 9:49:21 AM

'utf-8' codec can't decode byte 0xe1 in position 5: invalid continuation byte


Logger: custom_components.eufy_vacuum.tuya
Source: custom_components/eufy_vacuum/tuya.py:562
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 9:56:52 AM (2 occurrences)
Last logged: 9:56:52 AM

Failed to decrypt message from 30804162d8bfc0f179a5 (192.168.1.55:6668)


So for what ever reason the app says the IP of my vacuum is a public IP, which is not my public IP.  I have it reserved to 192.168.1.55 not sure if that's related but putting that public IP in does not work either.

**Comment by gmac0612** [comment]
I had the same thing with the app showing a public IP. Definitely check & keep the configured IP as the local one.

It's having problems decoding the Tuya part of it now. Check your configured local key is correct, a typo might make it break in this way. The key has also been known to change periodically.

**Comment by CyberDefenseTiger** [comment]
OK so that led me in the right direction.  I had to reregister my vacuum which updated everything.  I put in the new updated details and it works great now. Thank you so much for the help.  

If anyone reads this with similar issues it might be caused by changing public IPs causing token to change but the app not updating but i don't know that for sure.
